hydra:
    run:
        dir: outputs/memla/${edit_lang}/${expname}-${editor.learning_rate}-${seed}-${now:%Y-%m-%d-%H-%M-%S}
expname: simple_test

llm:
    model_name: "llama3-8b"
    layer_module: "model.layers.{}"
    mlp_c_fc_module: "mlp.up_proj"
    mlp_c_proj_module: "mlp.down_proj"

languages:
    - "en"
    - "zh"
    - "fr"
    - "de"
    - "it"
    - "es"
    - "pt"
    - "pl"
    - "ru"
    - "ja"
    - "ko"
    - "th"

editor:
    num_steps: 60
    learning_rate: 0.001   # 0.005

n_rank: 4

seed: 42
edit_lang: "en"
eval_langs:
  - "en"
  - "zh"
cross_langs:
  - "en"
  - "zh"
  - "fr"
data_fname: "./data/MLiKE_v2.json"
test_ids_fname: "./data/test_ids_2000.txt"
neuron_dir: "./data/neurons_MLiKE/"